<?php

namespace Tuchsoft\MoodleChecklist\Process;

abstract class AbstractIssuesProcess extends AbstractProcess
{
    /**
     * @var array Temporary storage for messages generated during parsing, not directly exposed to the caller.
     */
    protected array $messages = [];

    /**
     * @var array Stores the identified issues after parsing, intended for retrieval by the caller.
     */
    protected array $issues = [];

    /**
     * Executes the defined command and then parses its output for issues.
     *
     * This method extends the base `execute` functionality from `AbstractProcess`
     * by adding a subsequent step to parse the command's output. The results
     * of this parsing should populate the `$this->issues` property.
     *
     * @param float|null $timeout The maximum time (in seconds) the process is allowed to run.
     * Set to `null` for no timeout. Defaults to 60.0 seconds.
     * @return bool True if both the command execution and output parsing were successful, false otherwise.
     */
    public function execute(?float $timeout = 60.0): bool
    {
        if (!parent::execute($timeout)) {
            return false;
        }

        return $this->parseOutput();
    }

    /**
     * Parses the output from the executed command to extract relevant data or issues.
     *
     * This method is crucial for transforming the raw `stdout` and `stderr`
     * into structured information, which can then be stored in `$this->issues`
     * and intermediate messages in `$this->messages`.
     *
     * @return bool True if the parsing was successful and issues/messages were processed, false otherwise.
     */
    abstract protected function parseOutput(): bool;

    /**
     * Retrieves issues, applying a code to them.
     *
     * This method is intended to be implemented by child classes to define
     * how issues are retrieved or how a provided code influences the issues.
     *
     * @param string|null $code An optional code that could be applied to, or associated with, the issues.
     * @return Issue[] all the issue generated by the process
     */

    public function getIssues(?string $code): array {
        return $this->issues;
    }
}